version: "3"

services:
  db:
    image: postgres:15
    restart: always
    env_file:
      - ../.env
    volumes:
      - ../docker/data:/var/lib/postgresql/data
    ports:
        - "5432:5432"
  backend:
    build:
      context: ../
      dockerfile: deployment/Dockerfile
    restart: always
    env_file:
      - ../.env
    environment:
      - POSTGRES_HOST=db
    depends_on:
      - db
    ports:
      - "8000:8000"