version: "3"

volumes:
  postgres-data:
  static-data:
    

services:
  db:
    image: postgres:15
    restart: always
    env_file:
      - ../backend/.env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  backend:
    build:
      context: ../backend/
      dockerfile: Dockerfile
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
    restart: always
    env_file:
      - ../backend/.env
    environment:
      - POSTGRES_HOST=db
      - RABBITMQ_HOST=rabbitmq
    volumes:
      - static-data:/code/static
    depends_on:
      - db
    ports:
      - "8000:8000"
  rabbitmq:
    image: rabbitmq:3.10.7-management
    hostname: rabbitmq
    restart: always
    env_file:
      - ../backend/.env
    environment:
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,error},{default,error}] disk_free_limit 2147483648
    ports:
      - "15672:15672"
      - "5672:5672"
    # command: server /data --console-address ":9090"
  worker:
    build:
      context: ../backend/
      dockerfile: Dockerfile
    command: celery -A app.worker.celery worker --loglevel=info
    volumes:
      - ./project:/usr/src/app
    env_file:
      - ../backend/.env
    environment:
      - POSTGRES_HOST=db
      - RABBITMQ_HOST=rabbitmq
    depends_on:
      - backend
      - rabbitmq
      - db
  web:
    build:
      context: ../frontend/
      dockerfile: Dockerfile
    environment:
      - VITE_API_URL=http://localhost:8000

    ports:
      - "8080:5173"
